name: androidmakers_schedule
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # GraphQL
  ferry: 0.16.0+1
  gql_http_link: 1.0.1+1
  ferry_hive_store: 0.5.2

  # Appwrite
  appwrite: 12.0.1

  hive: 2.2.3
  hive_flutter: 1.1.0
  get_it: 7.6.8

  kotlin_scope_function: 1.0.2

  connectivity_plus: 6.0.1

  intl: ^0.19.0
  flutter_bloc: 8.1.5

  auto_size_text: ^3.0.0
  qr_flutter: 4.1.0
  flutter_svg: 2.0.10+1
  cached_network_image: 3.3.1
  window_manager: 0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

  ferry_generator: 0.10.0
  hive_generator: 2.0.1
  build_runner: 2.4.9

flutter:
  assets:
    - shorebird.yaml
    - assets/
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic